name: camera_example
description: Demonstrates how to use the camera plugin.
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"

dependencies:
  camera_frame:
    path: ../
  flutter:
    sdk: flutter
  path_provider: ^2.0.0
  video_player: ^2.7.0

dev_dependencies:
  build_runner: ^2.1.10
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  leak_tracker_flutter_testing: any

dependency_overrides: 
  camera_platform_interface_frame: ^2.10.10

flutter:
  uses-material-design: true
