name: camera_frame
description: A Flutter plugin for controlling the camera. Supports previewing
  the camera feed, capturing images and video, and streaming image buffers to
  Dart.
repository: https://github.com/zhukeev/camera_frame
issue_tracker: https://github.com/zhukeev/camera_frame/issues

version: 0.11.4

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: camera_android_frame
      ios:
        default_package: camera_avfoundation_frame

dependencies:
  camera_android_frame: ^0.10.24
  camera_avfoundation_frame: ^0.9.20+12
  camera_platform_interface_frame: ^2.10.12
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  leak_tracker_flutter_testing: any
  mockito: ^5.4.4
  plugin_platform_interface: ^2.1.7


topics:
  - camera
  - frame
